services:
  pg_jwt_auth:
    image: postgres:15-alpine
    container_name: pg_jwt_auth_container
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-jwt-auth-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer_jwt_auth_container
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-jwt-auth-data:
